# Generated by Django 3.1.5 on 2021-03-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_auto_20210303_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_categories',
        ),
        migrations.AddField(
            model_name='product',
            name='product_categories',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shopApp.productcategory'),
            preserve_default=False,
        ),
    ]
