# Generated by Django 3.1.5 on 2021-03-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_auto_20210303_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
